...

diff --git a/testing/x-cmd/APKBUILD b/testing/x-cmd/APKBUILD
--- a/testing/x-cmd/APKBUILD
+++ b/testing/x-cmd/APKBUILD
@@ -1,4 +1,3 @@
-
 # Contributor: Li Junhao <l@x-cmd.com>
 # Maintainer: zhengqiakai <zhengqiakai@x-cmd.com>
 pkgname=x-cmd
@@ -28,7 +27,7 @@ package() {
 	local _pkgdir="$pkgdir/usr/share/x-cmd/v/$_pkgsum"
 	local _pkgfile="$pkgdir/usr/share/x-cmd/v/$_pkgsum.tgz"
 	if [ ! -f "$_pkgfile" ]; then
-		printf "%s\n" "- I|x: Not found x-cmd pkg tgz file -> $_pkgfile" >/dev/tty
+		printf "%s\n" "- I|x: Not found x-cmd pkg tgz file -> $_pkgfile" >&2
 	else
 		printf "%s\n" "- I|x: Unpacking $_pkgfile to $_pkgdir" >&2
 		mkdir -p "$_pkgdir"
