community/py3-qt6: check python dependency info in prepare()
This commit introduces the _check_dep() function which is used in
prepare() to read python dependency information from the pyproject.toml
and PKG-INFO files, and check it against the versions of the
dependencies installed.

Yes its hacky, but I keep forgetting that riverbank doesn't put any
useful dependency version information in the release notes. They seem to
rely entirely on their python toolchain to get it right, which does not
work with our build process. With this code I will at least be pointed
in the right direction the next time the dependency chain breaks.

diff --git a/community/py3-qt6/APKBUILD b/community/py3-qt6/APKBUILD
--- a/community/py3-qt6/APKBUILD
+++ b/community/py3-qt6/APKBUILD
@@ -42,6 +42,52 @@ riscv64)
 	;;
 esac
 
+#
+# This function reads python dependency information for $_dep from $_dep_file,
+# using $_dep_regex, and compares the minimum required version with the
+# installed version of $_dep_pkg.
+#
+# The $_dep_regex must:
+#  1. be compatible with busybox sed's extended regex syntax
+#  2. match the entire line containing the needed version info
+#  3. capture the version number in capture group 1
+#
+_check_dep() {
+	if [ ! -f "$_dep_file" ]; then
+		echo "cant read python dependency info for $_dep from $_dep_file!"
+		exit 1
+	fi
+	_dep_need=$(sed -rn 's/'"$_dep_regex"'/\1/p' "$_dep_file")
+	if [ -z "$_dep_need" ]; then
+		echo "didnt find py dependency info for $_dep in $_dep_file!"
+		exit 1
+	fi
+	_dep_have=$(apk list --installed "$_dep_pkg" | head -n1 | \
+	    sed -rn 's/'"$_dep_pkg"'-(([[:digit:]]+\.?){1,3}).*/\1/p')
+	_dep_cmp=$(apk version -t "$_dep_have" "$_dep_need")
+	if [ $? != 0 ] || [ "$_dep_cmp" = "<" ]; then
+		echo "Fails $_dep version requirement: $_dep_have $_dep_cmp $_dep_need!"
+		exit 1
+	fi
+	echo "Satisfies $_dep version requirement: $_dep_have $_dep_cmp $_dep_need"
+}
+
+prepare() {
+	default_prepare
+
+	_dep=sip
+	_dep_file="$builddir/pyproject.toml"
+	_dep_regex='.*sip ?>= ?(([[:digit:]]+\.?){1,3}).*'
+	_dep_pkg=py3-sip
+	_check_dep
+
+	_dep=qt6-sip-module
+	_dep_file="$builddir/PKG-INFO"
+	_dep_regex='.*PyQt6-sip ?\(>=(([[:digit:]]+\.?){1,3}).*'
+	_dep_pkg=py3-pyqt6-sip
+	_check_dep
+}
+
 build() {
 	export CFLAGS="$CFLAGS -O2 -flto=auto"
 	export CXXFLAGS="$CXXFLAGS -O2 -flto=auto"
